### ISSUE TITLE
Rfactory opens multiple factory files

### ISSUE THREAD

**Issue by skarger** [christoomey/vim-rfactory#15]
Hello,

I tried Rfactory after hearing @christoomey and @derekprior talk about it on The Bike Shed. Seems very useful but I'm noticing something odd:

When I run `:Rfactory` with my cursor on a `create(:my_model)` expression, I expect it to open just `spec/factories/my_model.rb` but instead it opens a bunch of files. Each opened file is from `spec/factories/`. It might be opening each file that is referenced (directly or indirectly) from the target factory file, although not 100% sure about that.

Is this behavior intended?

**Comment by ogirginc** [comment]
I have the same problem. Unfortunately, this makes the plug-in not useable, due to keep adding files in background to my buffer! 😢

**Comment by phantomwhale** [comment]
Just found this plugin, thinking surely something exists for this, and got the same behaviour - paused for a long time then took me to one factory file, but polluted the open buffers list with tons of others.

Ah well, would have been a nice to have.

**Comment by kaka-ruto** [comment]
Happens for me too

**Comment by Seybo** [comment]
Having the same issue. And i suppose it's because my project factories are called `modelname_factories.rb`. Any workarounds maybe?

**Comment by christoomey** [comment]
Hey folks, unfortunately I don't have a great answer here, but I did want to at least comment to clarify. The plugin was designed in the context of a single file factory setup, and while I'd love to expand support for multiple factories, I don't know when or if I'll be able to get to that. 

For the time being, I'd only recommend trying to use the plugin in projects with a single factories.rb file.

**Comment by skarger** [comment]
Closing - works as intended.

To everyone looking for a solution: These days I use IntelliJ/RubyMine for development. It includes the "jump to factory" functionality, and similar features to toggle between a spec and production file, and dig through method definitions, including from gems.

I still love vim's keyboard design and responsiveness, but IntelliJ's source code tools and debugger are so helpful.
