### ISSUE TITLE
Support factories in a directory

### ISSUE THREAD

**Issue by geoffharcourt** [christoomey/vim-rfactory#4]
The generators (I know that's a bad word) for https://github.com/thoughtbot/factory_girl_rails generate a factory in `spec/factories` with the collection name of the model. Even independently of generators, this seems like a good idea, rather than having one enormous factories files. I'm very green with vimscript, but if there is a way to search for the factory definitions in a folder, it would erase a barrier I'm sure many users would have to using this plugin.

**Comment by christoomey** [comment]
Support for all valid factory locations added in https://github.com/christoomey/vim-rfactory/commit/b48288d0117ea1abede0c08c2c3f562be92e918d. Also, so nice to have you on the thoughtbot team now, @geoffharcourt.

**Comment by geoffharcourt** [comment]
Awesome addition to the repo. The feeling regarding my new employment is mutual, @christoomey.
