### ISSUE TITLE
Support `gf` to jump to the factory under the cursor

### ISSUE THREAD

**Issue by teoljungberg** [christoomey/vim-rfactory#9]
A naive implementation would be `nnoremap gf :Rfactory<cr>`, but since `gf` already is mapped to jump to files under the cursor. Maybe that will break?

**Comment by christoomey** [comment]
I worry about mapping over `gf` as it has existing functionality I would not want to lose. Also, I see this more as a ctags-esque lookup (find me the definition) than a go to file operation.

That said, I'm currently mapping to `<leader>gf`. I think I'm fine with just the commands and allowing users to create the mappings, perhaps with a quick example in the readme, but open to ideas.

**Comment by teoljungberg** [comment]
The ctags-argument makes total sense.
But, it got me thinking. I added these two lines to my `~/.ctags` file to get ctags support for factories and traits:

```
--regex-ruby=/^[ \t]*factory (:.*) do/\1/i,rspec shared_example/
--regex-ruby=/^[ \t]*trait (:.*) do/\1/i,rspec shared_example/
```
